redis:
  enabled: false

registry:
  replicaCount: 1
  # username: 
  # password: 

  maxUploadSize: 30m # maximum upload file
  host: registry.local
  garbageCron: 0 1 * * * # set the time to run docker image garbage collection, default is run daily at 00:00 AM
