{{- $fullName := include "registry.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{.Values.registry.maxUploadSize | default "30m" | squote}}
  labels:
    name: {{ $fullName }}-ingress
spec:
  {{- if .Values.registry.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.registry.host  | default "registry.local" | quote }}
    {{- if not .Values.registry.tls.secretName }}
    secretName: {{ $fullName }}-tls
    {{- else -}}
    secretName: {{ .Values.registry.tls.secretName }}
    {{ end -}}
  {{- end }}
  rules:
  - host: {{ .Values.registry.host | default "registry.local" | quote }}
    http:
      paths:
      - path: "/"
        {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ $fullName }}-server
            port: 
              number: 80
          {{- else }}
          serviceName: {{ $fullName }}-server
          servicePort: 80
          {{- end }}
