{{- $fullName := include "registry.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName}}-basic-auth
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.registry.username | default "admin" | b64enc }} 
  password: {{ .Values.registry.password | default "admin" | b64enc }}

---
{{- if not .Values.registry.tls.secretName }}
{{- if .Values.registry.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName}}-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.registry.tls.cert | b64enc }} 
  tls.key: {{ .Values.registry.tls.key | b64enc }} 
{{- end}}
{{- end}}