{{- $fullName := include "registry.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-server
spec:
  selector:
    app: {{ $fullName }}-server
  ports:
  - port: 80
    targetPort: 5000

---
{{- if not .Values.redis.externalHost }}
{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-redis
spec:
  selector:
    app: {{ $fullName }}-redis
  ports:
  - port: 6379
    targetPort: 6379
{{- end }}
{{- end }}