{{- $fullName := include "registry.fullname" . -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: myjob
spec:
  schedule: {{ .Values.registry.garbageCron | default "0 0 * * *" | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: registry-garbage-collect
            image: registry:2
            command:
            - /bin/sh
            - -c
            - bin/registry garbage-collect /etc/docker/registry/config.yml
            volumeMounts:
            - name: config 
              mountPath: /etc/docker/registry/config.yml
              subPath: config.yaml
            - name: data
              mountPath: /var/lib/registry
          restartPolicy: OnFailure
          volumes:
          - name: config
            configMap: 
              name: {{ $fullName }}-config
          - name: data
            hostPath:
              path: /tmp
              type: Directory
