{{- $fullName := include "registry.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ $fullName}}-basic-auth
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.registry.username | default "YWRtaW4K" | b64enc }} 
  password: {{ .Values.registry.password | default "YWRtaW4K" | b64enc }}